Create crazy_cake
SUSE/recipebook pull request #19
Opened 2021-03-25 20:54 UTC by SheilaghM

2021-03-25 21:59 UTC, dcermak requested changes
Please use the adoc format as the other recipes and add an entry to recipes.adoc as your recipe will otherwise not show up.

Besides that, looks good & tasty!

2021-03-26 02:27 UTC, SheilaghM commented
@dcermak - I think I got everything fixed. Please let me know if not.

2021-03-26 06:46 UTC, dcermak approved these changes

2021-03-26 06:47 UTC, merged

2021-03-26 06:47 UTC, dcermak commented
Thanks @SheilaghM, looks :yum:!