GrandmaBettyHarveysBrownies
SUSE/recipebook pull request #39
Opened 2021-03-26 22:19 UTC by markgharvey

Uploading GrandmaBettyHarveysBrownies

2021-03-26 23:14 UTC, dcermak reviewed
I've added suggestions including metric units

2021-03-26 23:14 UTC, dcermak commented on recipes/desserts/GrandmaBettyHarveysBrownies.adoc
> +|       | 1/2 stick | butter, room temperature |
```suggestion
| 75 g | 1/2 stick | butter, room temperature |
```
unsalted butter, I assume?

2021-03-26 23:14 UTC, dcermak commented on recipes/desserts/GrandmaBettyHarveysBrownies.adoc
> +|       | 1 cup     | white sugar |
```suggestion
| 200 g | 1 cup     | white sugar |
```

2021-03-26 23:14 UTC, dcermak commented on recipes/desserts/GrandmaBettyHarveysBrownies.adoc
> +|       | 1/2 cup   | all purpose flour |
```suggestion
| 60 g | 1/2 cup   | all purpose flour |
```

2021-03-26 23:14 UTC, dcermak commented on recipes/desserts/GrandmaBettyHarveysBrownies.adoc
> +|       | 1/2 cup + 1 tablespoon | cocoa powder |
```suggestion
| 65 g | 1/2 cup + 1 tablespoon | cocoa powder |
```

2021-03-26 23:14 UTC, dcermak commented on recipes/desserts/GrandmaBettyHarveysBrownies.adoc
> +|       | 3 tablespoons | canola oil |
```suggestion
| 45 ml | 3 tablespoons | canola oil |
```

2021-03-26 23:14 UTC, dcermak commented on recipes/desserts/GrandmaBettyHarveysBrownies.adoc
> +|       | 1 teaspoon    | vanilla |
```suggestion
| 5 ml | 1 teaspoon    | vanilla extract |
```

2021-03-27 18:32 UTC, rsimai requested changes
[id='sec.name_your_dish'] could be (e.g.) 'sec.GrandmaBettyHarveysBrownies'

2021-03-29 15:52 UTC, bmwiedemann commented
Please note that repo license changed to CC-BY-SA 4.0

2021-03-29 17:36 UTC, rsimai commented
@jeremy-moffitt would you know if the id in the recipe is OK with spaces?

2021-03-29 19:31 UTC, jeremy-moffitt commented
> @jeremy-moffitt would you know if the id in the recipe is OK with spaces?

It seems to work ok both in the github preview and in the build (no warnings), I'm assuming since its a quoted string that just about anything that can be url encoded can go in there. In my local copy it translates the current value to `sec.Grandma%20Betty%20Harvey` . A quick look at the asciidoctor docs indicates that its really driven by the output, so if we wanted to export to docbook (AFAIK we do not) there would be problems with ids that start with numbers for example. As long as we only care about the asciidoc rendering and the html rendering, we should be ok with spaces.

2021-03-29 21:15 UTC, rsimai commented
Thank you, let's merge then.

2021-03-29 21:15 UTC, rsimai approved these changes

2021-03-29 21:16 UTC, merged