Add recipe for pasta al limone
SUSE/recipebook pull request #7
Opened 2021-03-24 18:28 UTC by dcermak

2021-03-24 21:00 UTC, jeremy-moffitt requested changes
Thanks for submitting this recipe! It needs a slight tweak (empty line before a list) to fix the rendering, otherwise looks great!
![pasta_al_limone](https://user-images.githubusercontent.com/23247873/112382600-4894b900-8ca9-11eb-8632-04758f330b1b.png)

2021-03-24 21:00 UTC, jeremy-moffitt commented on recipes/main/pasta_al_limone.adoc
> +Ingredients:
I think you need an empty line underneath this for the rendering to be correct, otherwise it smushes it all into a paragraph rather than a list

2021-03-24 21:00 UTC, jeremy-moffitt commented on recipes/main/pasta_al_limone.adoc
> +Directions:
same as above, needs 1 empty line under `Directions:` or else everything renders as a blob

2021-03-24 22:43 UTC, dcermak commented
@jeremy-moffitt The formatting should be fixed now.

2021-03-25 14:54 UTC, jeremy-moffitt approved these changes
Looks great!

2021-03-25 14:54 UTC, merged